using KgCodegen.Core.Emit;
using KgCodegen.Core.Model;
using KgCodegen.Core.Ontology;
using KgCodegen.Core.Parsing;
using KgCodegen.Core.Spine;
using KgCodegen.Core.Validation;

var arguments = args.ToList();
string root = GetOption("--root") ?? Path.GetFullPath(Path.Combine(AppContext.BaseDirectory, "..", "..", "..", "..", "..", ".."));
string ontologyPath = GetOption("--ontology") ?? Path.Combine(root, "tools", "kg", "seed", "ontology.json");
bool check = arguments.Contains("--check", StringComparer.OrdinalIgnoreCase);

var graph = SpineCatalog.Create();
var resolver = new ModuleResolver();
var symbols = DomainSymbolIndex.Build(Path.Combine(root, "ECommerceApp.Domain"));
var entity = new EntityParser(resolver).Parse(Path.Combine(root, "ECommerceApp.Infrastructure"), symbols);
entity.Graph.MergeInto(graph);
var parsers = new (string Name, ParserResult Result)[]
{
    ("Entity", entity),
    ("Repository", new RepositoryParser(resolver).Parse(Path.Combine(root, "ECommerceApp.Domain"), graph.Nodes.Where(x => x.Label == "Entity").ToList())),
    ("Action", new ActionParser(resolver).Parse(Path.Combine(root, "ECommerceApp.Application")))
};

foreach (var parser in parsers)
{
    if (!ReferenceEquals(parser.Result, entity)) parser.Result.Graph.MergeInto(graph);
    foreach (var warning in parser.Result.Warnings) Console.WriteLine($"warning: {warning}");
    foreach (var warning in YieldTracker.Warnings(parser.Name, parser.Result.Graph.Nodes.Count)) Console.WriteLine($"warning: {warning}");
}

var report = GraphValidator.Validate(graph, OntologyLoader.Load(ontologyPath));
foreach (var warning in report.Warnings) Console.WriteLine($"warning: {warning}");
foreach (var error in report.Errors) Console.Error.WriteLine($"error: {error}");
foreach (var group in graph.Nodes.GroupBy(x => x.Label).OrderBy(x => x.Key)) Console.WriteLine($"{group.Key}: {group.Count()}");
Console.WriteLine($"Edges: {graph.Edges.Count}");
if (report.Errors.Count > 0) return 1;
if (!check)
{
    var output = GetOption("--out") ?? Path.Combine(GetOption("--out-dir") ?? Path.Combine(root, "tools", "kg"), $"kg-seed.{DateTime.UtcNow:yyyyMMddHHmmss}.cypher");
    Directory.CreateDirectory(Path.GetDirectoryName(output)!);
    File.WriteAllText(output, CypherEmitter.Emit(graph, ["// Generated by KgCodegen."]));
    Console.WriteLine($"Wrote {output}");
}
return 0;

string? GetOption(string name)
{
    var index = arguments.FindIndex(x => string.Equals(x, name, StringComparison.OrdinalIgnoreCase));
    return index >= 0 && index + 1 < arguments.Count ? arguments[index + 1] : null;
}