version: "3.8"

services:
    api:
        build:
            context: .
            dockerfile: Dockerfile-api
        container_name: api
        restart: unless-stopped
        ports:
          - 5001:80 
    
    web:
        build:
            context: .
            dockerfile: Dockerfile-web
        container_name: web
        restart: unless-stopped
        ports:
          - 5000:80 