// <auto-generated />
using System;
using ECommerceApp.Infrastructure.Supporting.Currencies;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECommerceApp.Infrastructure.Supporting.Currencies.Migrations
{
    [DbContext(typeof(CurrencyDbContext))]
    [Migration("20260314122159_OwnsOneCurrencyCodeDescription")]
    partial class OwnsOneCurrencyCodeDescription
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("currencies")
                .HasAnnotation("ProductVersion", "7.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ECommerceApp.Domain.Supporting.Currencies.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Currencies", "currencies");
                });

            modelBuilder.Entity("ECommerceApp.Domain.Supporting.Currencies.CurrencyRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CurrencyDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<decimal>("Rate")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.ToTable("CurrencyRates", "currencies");
                });

            modelBuilder.Entity("ECommerceApp.Domain.Supporting.Currencies.Currency", b =>
                {
                    b.OwnsOne("ECommerceApp.Domain.Supporting.Currencies.ValueObjects.CurrencyCode", "Code", b1 =>
                        {
                            b1.Property<int>("CurrencyId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("Code");

                            b1.HasKey("CurrencyId");

                            b1.HasIndex("Value")
                                .IsUnique()
                                .HasDatabaseName("IX_Currencies_Code")
                                .HasFilter("[Code] IS NOT NULL");

                            b1.ToTable("Currencies", "currencies");

                            b1.WithOwner()
                                .HasForeignKey("CurrencyId");
                        });

                    b.OwnsOne("ECommerceApp.Domain.Supporting.Currencies.ValueObjects.CurrencyDescription", "Description", b1 =>
                        {
                            b1.Property<int>("CurrencyId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("nvarchar(300)")
                                .HasColumnName("Description");

                            b1.HasKey("CurrencyId");

                            b1.ToTable("Currencies", "currencies");

                            b1.WithOwner()
                                .HasForeignKey("CurrencyId");
                        });

                    b.Navigation("Code")
                        .IsRequired();

                    b.Navigation("Description")
                        .IsRequired();
                });

            modelBuilder.Entity("ECommerceApp.Domain.Supporting.Currencies.CurrencyRate", b =>
                {
                    b.HasOne("ECommerceApp.Domain.Supporting.Currencies.Currency", null)
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
