using KgCodegen.Core.Emit;
using KgCodegen.Core.Model;
using KgCodegen.Core.Overrides;
using KgCodegen.Core.Parsing;
using KgCodegen.Core.Spine;

namespace KgCodegen.Tests;

public sealed class DeterminismTests
{
    [Fact]
    public void Full_real_repository_pipeline_emits_byte_identical_output()
    {
        var first = EmitRealGraph();
        var second = EmitRealGraph();

        Assert.Equal(first, second);
    }

    private static string EmitRealGraph()
    {
        var root = FindRepositoryRoot();
        var modules = OverridesLoader.Load(Path.Combine(root, "tools", "kg", "seed", "overrides.yaml")).Modules;
        var resolver = new ModuleResolver(modules.ToDictionary(module => module.Id, module => module.Path));
        var graph = SpineCatalog.Create(modules);
        var symbols = DomainSymbolIndex.Build(Path.Combine(root, "ECommerceApp.Domain"));
        var entity = new EntityParser(resolver).Parse(Path.Combine(root, "ECommerceApp.Infrastructure"), symbols);
        entity.Graph.MergeInto(graph);
        var repository = new RepositoryParser(resolver).Parse(
            Path.Combine(root, "ECommerceApp.Domain"),
            graph.Nodes.Where(node => node.Label == "Entity").ToList());
        repository.Graph.MergeInto(graph);
        var action = new ActionParser(resolver).Parse(Path.Combine(root, "ECommerceApp.Application"));
        action.Graph.MergeInto(graph);

        return CypherEmitter.Emit(graph, ["// Generated by KgCodegen."]);
    }

    private static string FindRepositoryRoot()
    {
        for (var directory = new DirectoryInfo(AppContext.BaseDirectory); directory is not null; directory = directory.Parent)
        {
            if (File.Exists(Path.Combine(directory.FullName, "ECommerceApp.sln")))
            {
                return directory.FullName;
            }
        }

        throw new DirectoryNotFoundException("Could not locate ECommerceApp repository root.");
    }
}
